language: minimal
services:
- docker
install:
- docker pull magland/hither2-dev:latest
- docker pull magland/kachery2
script:
- devel/test_in_docker.sh
after_success:
- bash <(curl -s https://codecov.io/bash) -F travis